# Generated by Django 4.0.4 on 2022-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('poorvika', models.CharField(max_length=255)),
                ('flipkart', models.CharField(max_length=255)),
                ('amazon', models.CharField(max_length=255)),
                ('croma', models.CharField(max_length=255)),
                ('reliance', models.CharField(max_length=255)),
                ('vijaysales', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
