# Generated by Django 4.0.6 on 2022-08-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_all_price_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeApplainces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('Brand', models.CharField(max_length=255)),
                ('Product', models.CharField(max_length=255)),
                ('Poorvika', models.CharField(max_length=255)),
                ('Sathya', models.CharField(max_length=255)),
                ('Vasanth', models.CharField(max_length=255)),
                ('Darling', models.CharField(max_length=255)),
                ('Viveks', models.CharField(max_length=255)),
                ('Croma', models.CharField(max_length=255)),
                ('Amazon', models.CharField(max_length=255)),
                ('Flipkart', models.CharField(max_length=255)),
                ('Reliance', models.CharField(max_length=255)),
                ('Tata_Cliq', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='All_Price',
            new_name='Poorvika',
        ),
    ]
